version: "3"
services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
  bgapi:
    image: 'matecz/bgapi'
    ports:
      - "8080:80"
  bglogger:
    image: 'matecz/bglogger'
    ports:
      - "8080:70"
volumes:
  rabbitmq_data:
    driver: local

  