version: "3"
services:
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  bglogger:
    image: matecz/bglogger
    expose:
      - "3000"
    restart: on-failure
    depends_on:
      - rabbitmq
  bgapi:
    image: matecz/bgapi
    ports:
      - "8080:80"
    restart: on-failure
    depends_on:
      - rabbitmq
  

  